In [1]:
import torch

In [4]:
random_vector = torch.randint(-100, 100, (4,))
random_vector

tensor([-41, -46,  67,   0])

In [6]:
tensor1 = torch.tensor([[0.2, 1.2], [2.3, 3.2], [4.5, 5.5]])
tensor1

tensor([[0.2000, 1.2000],
        [2.3000, 3.2000],
        [4.5000, 5.5000]])

In [7]:
zeros = torch.zeros((2, 3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
ones = torch.ones((3, 5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [10]:
input = torch.empty((3, 4))
input

tensor([[-1.8318e-04,  1.5162e-42,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [14]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [18]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [16]:
logspace = torch.logspace(start=-10, end=10, steps=6)
logspace

tensor([1.0000e-10, 1.0000e-06, 1.0000e-02, 1.0000e+02, 1.0000e+06, 1.0000e+10])

In [17]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [25]:
a = torch.empty((3, 2), dtype=torch.int64)
print(a)
empty_like = torch.empty_like(a)
print(empty_like)

tensor([[4650262600368,             0],
        [            0,             0],
        [            0,             0]])
tensor([[0, 0],
        [0, 0],
        [0, 0]])


In [26]:
a = torch.empty((3, 2), dtype=torch.int32)
print(a)
empty_like = torch.empty_like(a)
print(empty_like)

tensor([[-1186919328,        1082],
        [          0,           0],
        [          0,           0]], dtype=torch.int32)
tensor([[0, 0],
        [0, 0],
        [0, 0]], dtype=torch.int32)


In [27]:
a = torch.empty((3, 2), dtype=torch.float)
print(a)
empty_like = torch.empty_like(a)
print(empty_like)

tensor([[-1.8411e-04,  1.5162e-42],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]])
tensor([[-1.8411e-04,  1.5162e-42],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]])


In [29]:
import torch
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [60]:
%%time

start_time = time.time()
#matrix operation
zeros = torch.zeros((3, 4))
end_time = time.time()

elapsed_time = end_time - start_time
print(f'{elapsed_time:.8f}')

0.00000000
CPU times: total: 0 ns
Wall time: 998 µs


In [61]:
%%time

rand1 = torch.randn(100, 100, 100, 100).to(device)
rand2 = torch.randn(100, 100, 100, 100).to(device)

torch_rand1 = rand1.to(device)
torch_rand2 = rand2.to(device)
np_rand1 = rand1.cpu()
np_rand2 = rand2.cpu()

start_time = time.time()
# GPU_Pytorch matrix multiplication
torch_rand3 = (torch_rand1 @ torch_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f'{elapsed_time:.8f}')

start_time = time.time()
# Numpy matrix multiplication
np_rand3 = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f'{elapsed_time:.8f}')

#print('GPU_Pytorch: ', torch_rand3)
#print('CPU_Numpy: ', np_rand3)

0.00099730
0.14025092
CPU times: total: 1.97 s
Wall time: 2.23 s


In [62]:
# embeddings, torch.stack, torch.multinomial, torch.tril, torch.triu, input.T / input.transpose, nn.Linear, torch.cat, F.softmax (show all the examples of functions/methods with pytorch docs)


# Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])
# 10% or 0.1 => 0, 90% or 0.9 => 1. each probability points to the index of the probability in the tensor
# Draw 5 samples from the multinomial distribution
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([0, 1, 0, 1, 1, 1, 1, 1, 1, 1])


In [63]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [72]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [74]:
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [70]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [71]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [82]:
input = torch.randn(4, 3, 2)
print(input)
out = input.transpose(0, 2)
print(out)
print(out.shape)
out1 = out.transpose(1, 2)
print(out1)
print(out1.shape)

tensor([[[-0.1888,  0.4303],
         [-1.1499, -1.0432],
         [-1.2526,  1.1229]],

        [[ 1.2862,  0.7870],
         [-0.8411,  1.0077],
         [ 0.6904,  0.2301]],

        [[-2.6888,  0.1164],
         [-1.4084,  0.6388],
         [ 0.8038, -0.9506]],

        [[ 0.8082,  0.7009],
         [ 0.2260,  0.9579],
         [ 0.5093,  0.3698]]])
tensor([[[-0.1888,  1.2862, -2.6888,  0.8082],
         [-1.1499, -0.8411, -1.4084,  0.2260],
         [-1.2526,  0.6904,  0.8038,  0.5093]],

        [[ 0.4303,  0.7870,  0.1164,  0.7009],
         [-1.0432,  1.0077,  0.6388,  0.9579],
         [ 1.1229,  0.2301, -0.9506,  0.3698]]])
torch.Size([2, 3, 4])
tensor([[[-0.1888, -1.1499, -1.2526],
         [ 1.2862, -0.8411,  0.6904],
         [-2.6888, -1.4084,  0.8038],
         [ 0.8082,  0.2260,  0.5093]],

        [[ 0.4303, -1.0432,  1.1229],
         [ 0.7870,  1.0077,  0.2301],
         [ 0.1164,  0.6388, -0.9506],
         [ 0.7009,  0.9579,  0.3698]]])
torch.Size([2, 4, 3])


In [85]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [95]:
import torch.nn as nn

'''
Linear

(3, 3) -> input o - o output //3x3 Neuron layer
[10., 10., 10.]  \ /
                o - o
                 \ /
                o - o
          
y = weight*x + bias
'''

sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))
print(linear(sample).size())

tensor([ 1.4377, 10.5763, -9.5184], grad_fn=<SqueezeBackward4>)
torch.Size([3])


In [94]:
import torch.nn.functional as F

'''
Softmax

[1.0, 2.0, 3.0] -> (1.0).exp + (2.0).exp + (3.0).exp
-> 2.71 + 7.34 + 19.9 = 29.95

[2.71/29.95, 7.31/29.95, 19.9/29.95] -> [0.0900, 0.2447, 0.6652]
'''

# Create a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

# Apply softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [97]:
# Initialize an embedding layer
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# Apply the embedding layer
embedded_output = embedding(input_indices)

# The output will be a tensor of shape (4, 6), where 4 is the number of inputs
# and 6 is the dimensionality of the embedding vectors
print(embedded_output.shape)
print(embedded_output)

torch.Size([4, 6])
tensor([[ 1.2372,  1.0535,  0.9189, -0.1601, -1.3230, -0.3586],
        [ 1.7451, -0.8471,  1.2860, -1.2221, -0.3387,  1.1636],
        [ 0.7103,  0.8000, -0.0342,  1.0269,  0.7558,  1.0115],
        [-0.4200,  0.1601,  0.4518,  0.4846, -0.9585, -0.5519]],
       grad_fn=<EmbeddingBackward0>)


In [102]:
tensor1 = torch.tensor([[2, 3, 5], [21, 32, 51]])
tensor2 = torch.tensor([[30, 12], [20, 10], [15, 3]])

tensor3 = (tensor1 @ tensor2)
print(tensor3)

tensor3 = torch.matmul(tensor1, tensor2)
print(tensor3)

tensor([[ 195,   69],
        [2035,  725]])
tensor([[ 195,   69],
        [2035,  725]])


In [103]:
input = torch.rand((4, 8, 10))
B, T, C = input.shape
output = input.view(B*T, C)
print(output)
# print(input)
print(output[:, -1, :])

tensor([[2.3533e-01, 1.7748e-01, 4.7110e-01, 1.9177e-01, 7.8789e-01, 6.0240e-03,
         9.3237e-01, 2.7317e-01, 8.8571e-01, 2.0182e-01],
        [4.0063e-01, 1.9473e-01, 9.6008e-01, 5.2283e-01, 9.6149e-02, 2.1716e-01,
         1.1526e-02, 3.7960e-01, 1.5161e-02, 9.0926e-01],
        [1.7484e-01, 5.9678e-01, 9.5216e-01, 8.2961e-01, 6.3675e-01, 7.5803e-01,
         3.3504e-01, 6.2155e-01, 6.1346e-01, 4.2473e-01],
        [4.5266e-01, 4.9359e-01, 9.3405e-01, 9.5166e-01, 7.2624e-01, 9.8238e-01,
         3.2132e-01, 7.4366e-01, 3.0186e-01, 3.3946e-01],
        [3.0920e-01, 7.0991e-01, 3.2639e-01, 6.1380e-01, 9.2240e-01, 8.8394e-02,
         9.2615e-01, 5.4780e-01, 7.6604e-01, 3.5789e-01],
        [3.4429e-01, 7.5185e-01, 4.6891e-01, 8.2413e-01, 7.6864e-01, 3.1322e-01,
         4.3105e-01, 4.3521e-01, 2.5779e-01, 9.3287e-01],
        [9.7980e-01, 7.6119e-01, 1.0082e-01, 1.1536e-01, 2.1282e-01, 4.6055e-01,
         9.3405e-02, 2.6379e-01, 8.6855e-02, 8.4525e-01],
        [8.4931e-01, 4.6217

IndexError: too many indices for tensor of dimension 2

In [104]:
x = torch.tensor([10], dtype=torch.float32)
y = F.tanh(x)
print(y)

tensor([1.])
